language: python
python:
    - "3.6"
    - "3.7"

install:
    - python -m pip install --upgrade pip
    - pip install --pre -e . --ignore-installed llvmlite
    - pip install black

script:
    - pytest
    - black --diff --check kapre
    - black --diff --check tests

after_success:
    - coveralls
    - pip uninstall -y kapre

after_failure:
    - pip uninstall -y kapre
